// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSLUyZUXNPAwSUbF6jNO6clTL6EHi5dnY',
    appId: '1:1075269774837:web:abd8c5ba3b9571dc2284bc',
    messagingSenderId: '1075269774837',
    projectId: 'visionary-cash-check',
    authDomain: 'visionary-cash-check.firebaseapp.com',
    storageBucket: 'visionary-cash-check.firebasestorage.app',
    measurementId: 'G-2TDHZ69VMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASSTXgQ5679VYit3kmCD3cQNzXba8Ewzg',
    appId: '1:1075269774837:android:eacd1a56d581eec72284bc',
    messagingSenderId: '1075269774837',
    projectId: 'visionary-cash-check',
    storageBucket: 'visionary-cash-check.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXGip1PBgGj4e2uyltWN4iP4Csh4ydObs',
    appId: '1:1075269774837:ios:be0ca1832b59fec42284bc',
    messagingSenderId: '1075269774837',
    projectId: 'visionary-cash-check',
    storageBucket: 'visionary-cash-check.firebasestorage.app',
    iosClientId: '1075269774837-018o4dlpndm5ef4kvv1u7i8qmjrca6gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.visionaryCashCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXGip1PBgGj4e2uyltWN4iP4Csh4ydObs',
    appId: '1:1075269774837:ios:be0ca1832b59fec42284bc',
    messagingSenderId: '1075269774837',
    projectId: 'visionary-cash-check',
    storageBucket: 'visionary-cash-check.firebasestorage.app',
    iosClientId: '1075269774837-018o4dlpndm5ef4kvv1u7i8qmjrca6gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.visionaryCashCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSLUyZUXNPAwSUbF6jNO6clTL6EHi5dnY',
    appId: '1:1075269774837:web:455cb7eb44865e032284bc',
    messagingSenderId: '1075269774837',
    projectId: 'visionary-cash-check',
    authDomain: 'visionary-cash-check.firebaseapp.com',
    storageBucket: 'visionary-cash-check.firebasestorage.app',
    measurementId: 'G-6WVX4JQTFV',
  );
}
